### ISSUE TITLE
sewar uqi usage

### ISSUE THREAD

**Issue by canhastrytocode** [andrewekhalel/sewar#13]
Hi 
I am able to run **sewar uqi** from the command line, but have not been able to successfully use the function within a python script.

Considering the following snippet:

```
from sewar.full_ref import uqi
from PIL import Image

im = Image.open("arctic_fox_PNG41386.png")
im2 = Image.open("arctic_fox_PNG41386.png")

uqi(im, im2)
```
When I run this, I get the following error:
PngImageFile' object has no attribute 'shape

What object is uqi expecting? I have tried to put the path of the image directly into uqi but does not seem to expect a string value.

**Comment by andrewekhalel** [comment]
Hi @canhastrytocode,

all functions are expecting numpy arrays. You can use either opencv to read images or convert  PIL image to numpy array as follows.

```
from sewar.full_ref import uqi
from PIL import Image
import numpy as np

im = np.array(Image.open("arctic_fox_PNG41386.png"))
im2 = np.array(Image.open("arctic_fox_PNG41386.png"))

uqi(im, im2)
```

Best,
Andrew

**Comment by canhastrytocode** [comment]
Thank you sir!
