### ISSUE TITLE
how can we run this code for faster calculation on cuda gpu?

### ISSUE THREAD

**Issue by aamirk5** [andrewekhalel/sewar#15]
I'm getting this error when i'm trying to run on this code with gpu. could you please help?

Traceback (most recent call last):
  File "test_ssim.py", line 123, in <module>
    ps=psnr(image_b,image_a)
  File "C:\Users\Aamir\Anaconda3\envs\pytorch\lib\site-packages\sewar\full_ref.py", line 64, in psnr
    MAX = np.iinfo(GT.dtype).max
  File "C:\Users\Aamir\Anaconda3\envs\pytorch\lib\site-packages\numpy\core\getlimits.py", line 506, in __init__
    raise ValueError("Invalid integer data type %r." % (self.kind,))
ValueError: Invalid integer data type 'O'.

**Comment by andrewekhalel** [comment]
Hi @aamirk5,

Would you please send me the code snippet that causes this error?

**Comment by aamirk5** [comment]
@andrewekhalel here is the code... i'm not so good at programming, please forgive my mistakes...

import os
import numpy
import torch
import math
import cv2
import pandas as pd
from PIL import Image
from sewar.full_ref import uqi
from sewar.full_ref import psnr
from sewar.full_ref import ssim
from sewar.full_ref import vifp
from operator import add
import numpy as np
datapath=("./dataset")
path_a1=("a")
path_b=("b")
path_a=datapath + "/a"
path_b=datapath + "/b"
print(path_a)
print(path_b)
ps_=0
vi_=0
uq_=0
i = 0
ss_=[0,0]
psi=[]
vii=[]
ssi=[]
ssi_0=[]
ssi_1=[]
uqii=[]
img_name=[]
files_name = os.listdir(path_a)
for file in files_name:
    i+=1
    dim=(256,256)
    print(i)
    image_a_path = path_a +'/'+ file
    image_b_path = path_b +'/'+ file
    img_a = cv2.imread(image_a_path)
    image_a = cv2.resize(img_a, dim, interpolation =cv2.INTER_AREA)
    img_b = cv2.imread(image_b_path,1)
    image_b = cv2.resize(img_b, dim, interpolation =cv2.INTER_AREA)
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(device)
    image_a =torch.tensor(image_a, device=device).float()
    image_b =torch.tensor(image_b, device=device).float()
    ps=psnr(image_b,image_a)
    psi.append(ps)
    vi=vifp(image_b,image_a)
    vii.append(vi)
    ss=list(ssim(image_b,image_a))
    ssi.append(ss)
    uq=uqi(image_b,image_a)
    uqii.append(uq)
    ps_= ps_ + ps
    vi_= vi_ + vi
    ss = np.array(ss)
    ss_ = np.array(ss_)
    ss_= ss_ + ss
    uq_=uq_ + uq
    img_name.append(file)
    ssi_0.append(ss[0])
    ssi_1.append(ss[1])
    print('image_name:', file, 'PSNR:', ps, 'VIF:', vi, 'SSIM', ss, 'UQI:', uq)   
print(datapath)
print("===> Avg. PSNR: {:.4f} dB".format(ps_ / i))
print("===> Avg. SSIM1:", (ss_/i))
print("===> Avg. UQI: {:.4f} dB".format(uq_ / i))
print("===> Avg. VIF: {:.4f} dB".format(vi_ / i))

**Comment by andrewekhalel** [comment]
It looks like you are passing Tensor to the function. You should pass an image or a NumPy array.

**Comment by aamirk5** [comment]
@andrewekhalel yes for image is working,,,, but i want to use cuda for faster calculation.. is it possible?
and there is one more thing,, using these evaluation metrics function (given by sewar) i'm getting values far different from research paper values,,, PSNR's function is giving much liker values but other function values are very much different.. am i missing anything please help me out...

**Comment by zakajd** [comment]
Hi
For anyone else looking for GPU computation of metrics, check out PyTorch Image Quality library:
[github.com/photosynthesis-team/piq](https://github.com/photosynthesis-team/piq).
It contains almost all metrics from this repo + a lot of others and allows GPU computations which is much faster.
