### ISSUE TITLE
About Q index

### ISSUE THREAD

**Issue by JhonKS** [andrewekhalel/sewar#16]
Dear!
I thank for your package, but i need more metrics for pansharpening. Especially, Q index.
You can refer the following paper:A Global Quality Measurement of Pan-Sharpened Multispectral Imagery.
Thank you in advance.
Yours Sincerely.

**Comment by andrewekhalel** [comment]
Hi @JohnKS,

Have you checked the UQI implemented metric? I believe it's the Q index you need.
I will close the issue but feel free to reopen if needed!

Best,
Andrew
