### ISSUE TITLE
Compare two images

### ISSUE THREAD

**Issue by khawar512** [andrewekhalel/sewar#19]
I am comparing two images but getting an error

```
from sewar.full_ref import ssim
img_path1 = "/home/khawar/Desktop/Image-Quality/kodim01.png"
img_path = "/home/khawar/Desktop/Image-Quality/kodim01.png"
result = ssim(img_path, img_path1)
print(result)
```

**Comment by nelsoncsc** [comment]
A slightly modified version of your code should work:

`from sewar.full_ref import ssim
img_path1 = "/home/khawar/Desktop/Image-Quality/kodim01.png"
img_path = "/home/khawar/Desktop/Image-Quality/kodim01.png"
from skimage import io
img = io.imread(fname =img_path)
img1 = io.imread(fname =img_path1)
result = ssim(img, img)
print(result)`

**Comment by andrewekhalel** [comment]
Hi @RashiqAzhan 

Are you sure the image files are not corrupted? If so I would try a slightly different version with a package made specific to read tiff files
```python
from tifffile import tifffile
from sewar.full_ref import *


cover_image_path = "scikit_image\cover\cover_1.tiff"
stego_image_path = "scikit_image\stego\stego_1.tiff"

cover_image = tifffile.imread(fname=cover_image_path)
stego_image = tifffile.imread(fname=stego_image_path)

ssim(cover_image, stego_image)
```
Let me know how it goes. I will close the issue for now. Please reopen if the problem persists.
