### ISSUE TITLE
About ERGAS

### ISSUE THREAD

**Issue by fkmajiji** [andrewekhalel/sewar#20]
I am confused the code about ERGAS. I always used one code in matlab.  So I ported this code to Python：
`def ergas_matlab(GT,P,r=1):
	n_samples = GT.shape[0] * GT.shape[1]
	nb = GT.shape[2]
	#RMSE
	aux = np.sum(np.sum((P - GT)**2, 0), 0)/n_samples
	buff_aux = np.sum(np.sum((P - GT), 0), 0)/n_samples
	mean_x = np.sum(np.sum(P, 0), 0)/n_samples
	rmse_per_band = np.sqrt(aux)
	# ergas
	mean_y = np.sum(np.sum(GT, 0), 0)/n_samples
	ergas = 100*r*np.sqrt(np.sum((rmse_per_band/mean_y)**2)/nb)

	return ergas`

**Comment by andrewekhalel** [comment]
Hi @fkmajiji,
Can you please share the matlab reference you are using?

**Comment by fkmajiji** [comment]
The matlab reference is here [https://github.com/alfaiate/HySure/blob/master/src/utils/quality_assessment.m](url)

**Comment by andrewekhalel** [comment]
Hi again,
Thanks for sharing!

I published [a bug fix for ERGAS](https://github.com/andrewekhalel/sewar/commit/56be3556de9917e0c6594b134ddf25d7835523a0), please update your Sewar version to 0.4.6
