### ISSUE TITLE
How  to calculate the SSIM between two images

### ISSUE THREAD

**Issue by saqibnaziir** [andrewekhalel/sewar#29]
Helloo, everyone. 

Can anyone please tell me how you are calculating the SSIM between Target and Prediction image?

I tried 
SM = ssim(pred,target)

but i got the error.

**Comment by andrewekhalel** [comment]
Please check [README](https://github.com/andrewekhalel/sewar/blob/master/README.md) file for examples. 

If your problem persists please share the following:
- OS version
- Sewar Version
- Python Version
-  Error stack trace
