### ISSUE TITLE
MSSSIM sometimes returns 'nan'

### ISSUE THREAD

**Issue by simon-bre** [andrewekhalel/sewar#3]
..and this is the warning that comes with it:

````
[...]\sewar\full_ref.py:298: RuntimeWarning: invalid value encountered in power
  return (np.prod(mcs[0:scales-1] ** weights[0:scales-1]) * \
[...]\sewar\full_ref.py:299: RuntimeWarning: invalid value encountered in double_scalars
  (mssim[scales-1] ** weights[scales-1]))
````

**Comment by andrewekhalel** [comment]
Hello @51m0n0m15 ,

Thanks for reporting this. I have just merged a pull request that should fix the bug. Please update your sewar installation
```
pip install -U sewar
```
and try to reproduce the same bug. If still present, let me know.

**Comment by andrewekhalel** [comment]
Thanks @simon-bre!

I checked against the [original matlab implementation](https://github.com/gregfreeman/image_quality_toolbox/blob/master/msssim.m) and yes my implementation had some bugs that I fixed over last weekend (Hopefully!) 

Best,
Andrew
