### ISSUE TITLE
circular import problem

### ISSUE THREAD

**Issue by alexfilothodoros** [andrewekhalel/sewar#30]
Hello,

I have just installed sewar via pip on win10.

There is a problem. I cannot import full_ref.

The line

_from sewar import full_ref_

fails with the message:

[cannot import name 'full_ref' from partially initialized module 'sewar' (most likely due to a circular import)]()

Any ideas, why is this happening? What more info should I provide?

Cheers

**Comment by andrewekhalel** [comment]
Hi,

Can you please provide the following:
- Sewar version
- Python version
- Stack trace of the error

Thanks

**Comment by alexfilothodoros** [comment]
Hi,
Thanks for the reply.

sewar 0.4.5
python 3.9.7

 in <module> ----> 1[ from sewar import full_ref]()
ImportError: cannot import name 'full_ref' from partially initialized module 'sewar' (most likely due to a circular import)

**Comment by andrewekhalel** [comment]
Are you naming your file script `sewar.py`?

**Comment by alexfilothodoros** [comment]
oops! Thanks for that.
