### ISSUE TITLE
ERGAS extremely high 

### ISSUE THREAD

**Issue by pgreendale** [andrewekhalel/sewar#33]
Situation: 
tried to compute ERGAS values for fused image pairs and got extreme high values back, in the order of 100.000's.  Even for relatively similar images with high CC>98 , Q>95 and small RMSE~30 for RGB images, I got an ergas of >2000. 

As I look into publications for similar scenarios
https://www.researchgate.net/figure/ERGAS-values-for-fused-and-original-images_tbl2_262601486   the ergas should be much smaller, I would expect values around 10-15 for my application from visual inspection.

Are there any specific requirements regarding image data format, normalization etc? Looked at the code but didnt found a bug at a first glance.

**Comment by X-TRON404** [comment]
Any solution/reasoning on this? I am facing the same issue.

**Comment by andrewekhalel** [comment]
Hi,
Apologies for the delay

I published [a bug fix for ERGAS](https://github.com/andrewekhalel/sewar/commit/56be3556de9917e0c6594b134ddf25d7835523a0), please update your sewar version to 0.4.6
