### ISSUE TITLE
Any plan to add PSNR-B[1]?

### ISSUE THREAD

**Issue by jxgu1016** [andrewekhalel/sewar#4]
1. Yim, Changhoon, and Alan Conrad Bovik. "Quality assessment of deblocked images." IEEE Transactions on Image Processing 20.1 (2011): 88-98.

**Comment by andrewekhalel** [comment]
I will check this out! Thanks

**Comment by andrewekhalel** [comment]
Implemented at Merge Request #9

**Comment by jxgu1016** [comment]
Glad to hear it and thank you all！
