### ISSUE TITLE
about sam

### ISSUE THREAD

**Issue by jianyuan2015** [andrewekhalel/sewar#5]
the definition of sam is different from codes that calculate sam

**Comment by andrewekhalel** [comment]
Hello @jianyuan2015,

Would you please supply the codes you are comparing to?

**Comment by fkmajiji** [comment]
In my opinion, if  the size of input data GT is "[M, N, K]", where K is number of spectral band, the code shouble be like this:
```
GT = GT.reshape((GT.shape[0]*GT.shape[1],GT.shape[2]))
P = P.reshape((P.shape[0]*P.shape[1],P.shape[2]))
N = GT.shape[0]
sam_angles = np.zeros(N)
for i in range(GT.shape[0]):
      val = np.clip(np.dot(GT[i,:],P[i,:]) / (np.linalg.norm(GT[i,:])*np.linalg.norm(P[i,:])),-1,1)
      sam_angles[i] = np.arccos(val)
```

**Comment by andrewekhalel** [comment]
Hi @fkmajiji,

I think the current implementation is the correct one. We use the K (spectral band) as N. See example Matlab implementation [here](https://github.com/davidkun/HyperSpectralToolbox/blob/master/functions/hyperSam.m).

Closing this now. Feel free to reopen if you disagree

**Comment by fkmajiji** [comment]
I'm sorry, I saw the example Matlab implementation you mentioned and still think the current implementation is not correct. The introduction of Matlab function in [https://github.com/davidkun/HyperSpectralToolbox/tree/master/functions](url) has said "N The total number of pixels." and "p Number of bands."
